---
- name: Check results
  hosts: all

  tasks:
    - name: Check index.html
      uri:
        url: "http://{{ item }}"
        return_content: yes
      register: this
      failed_when: "'ansible' not in this.content"
      loop: "{{ groups['webservers'] }}"
      delegate_to: localhost

