---
name: Test
on: push

jobs:
  test:
    name: Test Job
    runs-on: self-hosted
    steps:
       - name: Test Run
         env:
           TEST_URL: ${{ secrets.TEST_URL }}
         run: curl "${TEST_URL}" 

